### ISSUE TITLE
Week 1 Checklist

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/tweepypoll#1]
- [x] Teamwork contract
- [x] Pick a topic
- [x] Project structure: Initiate a public repo
- [x] Project structure: Add contributors 
- [x] Project structure: Edit CONDUCT.md to to include the code of conduct
- [x] Project structure: Edit CONTRIBUTING.md to reflect the collaboration strategy
- [x] Project structure: Edit README.md to include a summary paragraph, functions, etc.
- [ ] Function specification: Add docstrings for all functions
- [x] Manage issues
- [ ] Canvas submission: URL of repo + URL of release + Teamwork contract

**Comment by gn385x** [comment]
Hey @xiangwxt and @Radascript , let's follow this checklist to keep track of our progress and make sure that we are taking care of all requirements!
