### ISSUE TITLE
Milestone 1 submission

### ISSUE THREAD

**Issue by gn385x** [UBC-MDS/tweepypoll#6]
For week 1, @Radascript will be our submitter. 

Here's the submission checklist:
- [ ] URL of our public project’s repo: https://github.com/UBC-MDS/tweepypoll
- [ ] URL of our release on our project repo named v0.1.0
- [ ] Paste the content of our teamwork contract: https://docs.google.com/document/d/1ZDTIHp0T599U0Ur5y7okf_Faa0Zia0Ljs_g7Mx0F4dU/edit#heading=h.yf2lf3rhrc14
